# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-20 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=32, verbose_name='歌名')),
                ('singer', models.CharField(max_length=32, null=True, verbose_name='歌手')),
                ('createTime', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
        ),
    ]
